spring.application.name=global-booking-functions
#twilio.accountSid=AC6fec8f6bd705d575f72700d38907d1d8
#twilio.authToken=85dadf66b11fc821eba7626849a5dfd9
#twilio.phoneNumber=+17405733897

spring.data.redis.host=localhost
spring.data.redis.port=6379

#Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/MkTotalcareDB
#spring.datasource.username=postgres
#spring.datasource.password=1234
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Render
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

